-- CreateTable
CREATE TABLE `Ads` (
    `id` VARCHAR(191) NOT NULL,
    `yearsPlaying` VARCHAR(191) NOT NULL,
    `nickName` VARCHAR(191) NOT NULL,
    `idDiscord` VARCHAR(191) NOT NULL,
    `startPlay` VARCHAR(191) NOT NULL,
    `endPlay` VARCHAR(191) NOT NULL,
    `chatVoice` VARCHAR(191) NOT NULL,
    `daysPlaying` VARCHAR(191) NOT NULL,
    `CreatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ModifiedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `gamesId` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Games` (
    `id` VARCHAR(191) NOT NULL,
    `nameGame` VARCHAR(191) NOT NULL,
    `imgUrl` VARCHAR(191) NOT NULL,
    `CreatedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ModifiedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
